# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qh_t8P0Jt689VHZV-i607NrPJKNhrMVu
"""

import pandas as pd

df = pd.read_csv("student.csv")

df.head()

grp = df.groupby(["Name","Class"])

grp

grp.groups

list(grp)

df1 = df['Class'].unique()

writer = pd.ExcelWriter('pandas_sample.xlsx',engine= 'openpyxl')
for i in df1:
  df[df['Class']==i].to_excel(writer,sheet_name=i,index = False)
writer.save()









df = pd.read_csv("sysmexdata24.csv")

df.head() #returns the first 5 rows of the dataset

df.tail() #returns the last 5 rows of the dataset

df.shape #returns the dimensions of the dataframe

df.columns.tolist() #extract all the column names as a list

df.describe() #shows count, mean, std etc. for each column

df.max() #returns max value for all columns

df.mean(axis='index') #returns the mean of that column

df['WBC'].argmax()

df['WBC'].value_counts() #shows how many times each item appears in the column

corr = df["HGB"].corr(df["MCV"]) #find coorelation between 2 columns

corr

# Create Graph

import seaborn as sns

sns.barplot(df['HGB'],df['MCV'])

pd.crosstab(df['HGB'],df['MCHC'])

import matplotlib.pyplot as plt

fig = sns.boxplot(df['HGB'])

fig = sns.boxplot(df['LYMPH%'])

sns.pairplot(df)



dff = pd.read_csv("sysmexdata24.log")

dff





lines = []

a_file = open("sysmexdata24.log", "r")

list_of_lists = []
for line in a_file:
  stripped_line = line.strip()
  line_list = stripped_line.split()
  list_of_lists.append(line_list)

a_file.close()

print(list_of_lists)



